config/routes.rb
MembersAlsacedigitale::Application.routes.draw do
  devise_for :users

  resources :users, only: [] do
    collection do 
      get 'profile'
    end
  end
  root to: "application#index"

  resources :payments, only: [] do
    collection do
      get 'subscription_confirm'
      get 'subscription'
      get 'subscription_checkout'
      get 'thank_you'
      get 'mypayments'
    end
  end

  namespace :admin do
    root to: "users#index"
    resources :users
  end

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :manage, User, :user_email => user.email
  end
end

class AdminAbility
  include CanCan::Ability

  def initialize(user)
    can :manage, User
  end
end

app/models/payment.rb
class Payment
  include Mongoid::Document
  include Mongoid::Timestamps

  class CheckPaymentValidator < ActiveModel::Validator
    def validate(record)
      if record.mode == "Bank Check" && (check_reference == nil || check_reference == "")
        record.errors[:base] << "Payment by bank check must have a reference"
      end
    end
  end
  class TransferPaymentValidator < ActiveModel::Validator
    def validate(record)
      if record.mode == "Transfer" && (transfer_reference == nil || transfer_reference == "")
        record.errors[:base] << "Payment by transfer must have a reference"
      end
    end
  end

  field :date, type: Date
  field :amount, type: Float
  field :mode, type: String
  field :check_reference, type: String
  field :transfer_reference, type: String

  validates :mode, inclusion: { in: ["Bank Check", "Cash", "Transfer", "Paypal"] } 
  validates_with CheckPaymentValidator
  validates_with TransferPaymentValidator

  belongs_to :user
  ##Paypal

  def self.conf
    @@gateway_conf ||= YAML.load_file(Rails.root.join('config/gateway.yml').to_s)[Rails.env]
  end

  def setup_payement(options)
    gateway.setup_payement(amount * 100, options)
  end

  def redirect_url(token)
    gateway.redirect_url(token)
  end

  def purchase(options={}) 
      self.status = PROCESSING  
      #:ip       => request.remote_ip,
      #:payer_id => params[:payer_id],
      #:token    => params[:token]
      response = gateway.purchase(amt, options)      
      if response.success?       
        self.transaction_num = response.params['transaction_id']       
        self.status = SUCCESS     
      else       
        self.status = FAILED     
      end     
      return self   
    rescue Exception => e     
      self.status = FAILED     
      return self   
    end

  private   
  def gateway 
    ActiveMerchant::Billing::Base.mode = auth['mode'].to_sym 
    ActiveMerchant::Billing::PaypalExpressGateway.new(
      :login => auth['login'], :password => auth['password'],
      :signature => auth['signature']) 
  end

  def auth
    self.class.conf
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""
  
  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String
  #

  field :admin, type: Boolean, default: false
  field :role, type: String, default: "Member"
  field :first_name, type: String
  field :last_name, type: String
  field :birth_date, type: Date
  field :birth_place, type: String

  field :street, type: String
  field :zipcode, type: Integer
  field :city, type: String
  field :country, type: String, default: "France"

  field :job_position, type: String
  field :personal_phone, type: String
  field :professional_phone, type: String
  field :subscription_date, type: Date
  field :last_renewal_date, type: Date

  field :flex_days, type: Integer, default: 0

  validates_presence_of :first_name, :last_name, :street, :zipcode, :city, :country, :email

  has_many :payments

  before_create do |user|
    user.flex_days = 2
  end

  def is_active?
    if last_renewal_date == nil
      false
    else
      DateTime.now - last_renewal_date < 1.year
    end
  end

  def is_admin?
    admin
  end

  def address
    "#{street} #{zipcode} #{city} #{country}"
  end

  def to_s
    "#{first_name} #{last_name}"
  end
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  before_action :authenticate_user!

  before_action :ensure_user_is_admin!

  protected
  def ensure_user_is_admin!
    raise CanCan::Unauthorized unless current_user.admin?
  end

  protected
  def current_ability
    AdminAbility.new(current_user)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
	def index
  	@users = User.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < BaseController
  before_action :registration_permitted_parameters, if: :devise_controller?

  # Doesn't work !!!
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

  def index
    redirect_to :controller => 'users', :action => 'profile'
  end

    def registration_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) do |u|
        u.permit :first_name, :last_name, :email, :password, :street, :zipcode, :city, :country, :birth_date, :birth_place, :job_position, :personal_phone, :professional_phone
      end
    end
end

app/controllers/base_controller.rb
class BaseController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action do 
    if user_signed_in?
      if !current_user.is_active?
        flash[:error] = "validity"
      end
    end
  end
end

app/controllers/payments_controller.rb
class PaymentsController < BaseController
  include ActiveMerchant::Billing
  before_action :authenticate_user!

  def subscription_checkout
    setup_response = gateway.setup_purchase 2000,
      ip:                 request.remote_ip,
      return_url:         url_for(action: 'subscription_confirm', only_path: false),
      cancel_return_url:  url_for(action: 'mypayments', only_path: false)
    
    redirect_to gateway.redirect_url_for(setup_response.token)
  end

  def subscription_confirm
    #token=EC-680659030C156364M&PayerID=KNNAZL6NLEN6W
    @payement = Payment.new
    @payment.date = Time.now.to_datetime
    @payment.amount = 20
    @payment.mode = 'paypal'


    raise 'Hello'
    # @payment.transfer_reference = x

    @payment.save()

  end

  def subscription
		@payement = Payment.new  
	end

  def mypayments
    @payments = Payments.where(user: current_user)
  end

  private

  def gateway
    @gateway ||= PaypalExpressGateway.new(
      login:  ENV['PAYPAL_LOGIN'],
      password:  ENV['PAYPAL_PASSWORD'],
      signature:  ENV['PAYPAL_SIGNATURE']
    )
  end

  def subscription_confirm
    redirect_to action: 'index' unless params[:token]

    details_response = gateway.details_for(params[:token])

    if !details_response.success?
      @message = details_response.message
      render action: 'error'
      return 
    end
    @address = details_response.address
  end
end

app/controllers/users_controller.rb
class UsersController < BaseController
  before_action :authenticate_user!

  def profile
  	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/admin/index.html.haml
%h1 Liste des utilisateurs

%table.table
  %thead
    %tr
      %th Prénom
      %th Nom
      %th Adresse
      %th Téléphone
      %th Dernière cotisation
      %th Cotisation
  %tbody
    - User.all.each do |u|
      %tr
        %td=u.first_name
        %td=u.last_name
        %td=u.address
        %td
          = u.personal_phone 
          = " / #{u.professional_phone}" if u.professional_phone
        %td= u.last_renewal_date
        - if u.is_active?
          %td.user-active
        - else
          %td.user-late

app/views/admin/users/index.html.haml
= render 'shared/top'

%h1 Liste des utilisateurs

%table.table
  %thead
    %tr
      %th Prénom
      %th Nom
      %th Adresse
      %th Téléphone
      %th Dernière cotisation
      %th Cotisation
  %tbody
    - @users.each do |u|
      %tr
        %td=u.first_name
        %td=u.last_name
        %td=u.address
        %td
          = u.personal_phone 
          = " / #{u.professional_phone}" if u.professional_phone
        %td= u.last_renewal_date
        - if u.is_active?
          %td.user-active
        - else
          %td.user-late

app/views/application/_flash.html.haml
- if error = flash[:error]
  .alert.alert-error
    - if error == "validity"
      Votre cotisation n'est pas valide ! Veuillez mettre à jour votre cotisation ?
      = link_to "Payez maintenant", subscription_payments_path
    - else
      = error

app/views/application/index.html.haml
/ = render 'shared/top'

/ - if user_signed_in?
/   %h2= "Connecté en tant que #{current_user}"
/   %p
/     = link_to "Mon profil", profile_users_path
/   = link_to "Se déconnecter", destroy_user_session_path, method: "DELETE"
/ - else
/   %p
/     = link_to "Se connecter à son espace membre", user_session_path
/     %br
/     = link_to "Adhérer à l'association", new_user_registration_path


!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %title Bootstrap, from Twitter
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/
    / Le styles
    %link{:href => "../assets/css/bootstrap.css", :rel => "stylesheet"}/
    :css
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
        %link{:href => "../assets/css/bootstrap-responsive.css", :rel => "stylesheet"}/
    / HTML5 shim, for IE6-8 support of HTML5 elements
    /[if lt IE 9]
      <script src="../assets/js/html5shiv.js"></script>
    / Fav and touch icons
    %link{:href => "../assets/ico/apple-touch-icon-144-precomposed.png", :rel => "apple-touch-icon-precomposed", :sizes => "144x144"}/
    %link{:href => "../assets/ico/apple-touch-icon-114-precomposed.png", :rel => "apple-touch-icon-precomposed", :sizes => "114x114"}/
    %link{:href => "../assets/ico/apple-touch-icon-72-precomposed.png", :rel => "apple-touch-icon-precomposed", :sizes => "72x72"}/
    %link{:href => "../assets/ico/apple-touch-icon-57-precomposed.png", :rel => "apple-touch-icon-precomposed"}/
    %link{:href => "../assets/ico/favicon.png", :rel => "shortcut icon"}/
  %body
    .navbar.navbar-inverse.navbar-fixed-top
      .navbar-inner
        .container
          %button.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse", :type => "button"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          / %a.brand{:href => "#"} Project name
          %li.brand Alsace Digitale
          .nav-collapse.collapse
            %ul.nav
              %li.active
                %a{:href => "#"} Home
              %li
                %a{:href => "#about"} About
              %li
                %a{:href => "#contact"} Contact
              / %li.dropdown
              /   %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              /     Dropdown
              /     %b.caret
              /   %ul.dropdown-menu
              /     %li
              /       %a{:href => "#"} Action
              /     %li
              /       %a{:href => "#"} Another action
              /     %li
              /       %a{:href => "#"} Something else here
              /     %li.divider
              /     %li.nav-header Nav header
              /     %li
              /       %a{:href => "#"} Separated link
              /     %li
              /       %a{:href => "#"} One more separated link
            %form.navbar-form.pull-right
              %input.span2{:placeholder => "Email", :type => "text"}/
              %input.span2{:placeholder => "Password", :type => "password"}/
              %button.btn{:type => "submit"} Sign in
          / /.nav-collapse
    = yield
      
    %hr/
    %footer
    %p © Company 2013
    / /container
    /
      Le javascript
      \==================================================
    / Placed at the end of the document so the pages load faster
    %script{:src => "../assets/js/jquery.js"}
    %script{:src => "../assets/js/bootstrap-transition.js"}
    %script{:src => "../assets/js/bootstrap-alert.js"}
    %script{:src => "../assets/js/bootstrap-modal.js"}
    %script{:src => "../assets/js/bootstrap-dropdown.js"}
    %script{:src => "../assets/js/bootstrap-scrollspy.js"}
    %script{:src => "../assets/js/bootstrap-tab.js"}
    %script{:src => "../assets/js/bootstrap-tooltip.js"}
    %script{:src => "../assets/js/bootstrap-popover.js"}
    %script{:src => "../assets/js/bootstrap-button.js"}
    %script{:src => "../assets/js/bootstrap-collapse.js"}
    %script{:src => "../assets/js/bootstrap-carousel.js"}
    %script{:src => "../assets/js/bootstrap-typeahead.js"}

app/views/application/tmp.html.haml
/ Main hero unit for a primary marketing message or call to action
      .hero-unit
        %h1 Hello, world!
        %p This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.
        %p
          %a.btn.btn-primary.btn-large{:href => "#"} Learn more »
      / Example row of columns
      .row
        .span4
          %h2 Heading
          %p Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
          %p
            %a.btn{:href => "#"} View details »
        .span4
          %h2 Heading
          %p Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
          %p
            %a.btn{:href => "#"} View details »
        .span4
          %h2 Heading
          %p Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.
          %p
            %a.btn{:href => "#"} View details »

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Gestion des membres d'Alsace Digitale
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags

  %body
    .container
      = yield

app/views/layouts/base.html.haml
/ !!!
/ %html
/   %head
/     %title Gestion des membres d'Alsace Digitale
/     = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
/     = javascript_include_tag "application", "data-turbolinks-track" => true
/     = csrf_meta_tags

/   %body
/     .container
/       = yield

/ = render 'shared/top'

/ - if user_signed_in?
/   %h2= "Connecté en tant que #{current_user}"
/   %p
/     = link_to "Mon profil", profile_users_path
/   = link_to "Se déconnecter", destroy_user_session_path, method: "DELETE"
/ - else
/   %p
/     = link_to "Se connecter à son espace membre", user_session_path
/     %br
/     = link_to "Adhérer à l'association", new_user_registration_path


!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %title Alsace Digitale - Gestion des membres
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/

    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags

    / Le styles
    %link{:href => "../assets/css/bootstrap.css", :rel => "stylesheet"}/
    :css
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
        %link{:href => "../assets/css/bootstrap-responsive.css", :rel => "stylesheet"}/
    / HTML5 shim, for IE6-8 support of HTML5 elements
    /[if lt IE 9]
      <script src="../assets/js/html5shiv.js"></script>
    / Fav and touch icons
    %link{:href => "../assets/ico/apple-touch-icon-144-precomposed.png", :rel => "apple-touch-icon-precomposed", :sizes => "144x144"}/
    %link{:href => "../assets/ico/apple-touch-icon-114-precomposed.png", :rel => "apple-touch-icon-precomposed", :sizes => "114x114"}/
    %link{:href => "../assets/ico/apple-touch-icon-72-precomposed.png", :rel => "apple-touch-icon-precomposed", :sizes => "72x72"}/
    %link{:href => "../assets/ico/apple-touch-icon-57-precomposed.png", :rel => "apple-touch-icon-precomposed"}/
    %link{:href => "../assets/ico/favicon.png", :rel => "shortcut icon"}/
  %body
    .navbar.navbar-inverse.navbar-fixed-top
      .navbar-inner
        .container
          %button.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse", :type => "button"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          / %a.brand{:href => "#"} Project name
          %li.brand Alsace Digitale
          .nav-collapse.collapse
            %ul.nav
              %li.active
                %a{:href => "#"} Home
              %li
                %a{:href => "#about"} About
              %li
                %a{:href => "#contact"} Contact
              / %li.dropdown
              /   %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              /     Dropdown
              /     %b.caret
              /   %ul.dropdown-menu
              /     %li
              /       %a{:href => "#"} Action
              /     %li
              /       %a{:href => "#"} Another action
              /     %li
              /       %a{:href => "#"} Something else here
              /     %li.divider
              /     %li.nav-header Nav header
              /     %li
              /       %a{:href => "#"} Separated link
              /     %li
              /       %a{:href => "#"} One more separated link
            %form.navbar-form.pull-right
              / %input.span2{:placeholder => "Email", :type => "text"}/
              / %input.span2{:placeholder => "Password", :type => "password"}/
              / %button.btn{:type => "submit"} Sign in
          / /.nav-collapse
    .container
      = yield
      
      %hr/
      %footer
      %p © Alsace Digitale 2013
    / /container
    /
      Le javascript
      \==================================================
    / Placed at the end of the document so the pages load faster
    %script{:src => "../assets/js/jquery.js"}
    %script{:src => "../assets/js/bootstrap-transition.js"}
    %script{:src => "../assets/js/bootstrap-alert.js"}
    %script{:src => "../assets/js/bootstrap-modal.js"}
    %script{:src => "../assets/js/bootstrap-dropdown.js"}
    %script{:src => "../assets/js/bootstrap-scrollspy.js"}
    %script{:src => "../assets/js/bootstrap-tab.js"}
    %script{:src => "../assets/js/bootstrap-tooltip.js"}
    %script{:src => "../assets/js/bootstrap-popover.js"}
    %script{:src => "../assets/js/bootstrap-button.js"}
    %script{:src => "../assets/js/bootstrap-collapse.js"}
    %script{:src => "../assets/js/bootstrap-carousel.js"}
    %script{:src => "../assets/js/bootstrap-typeahead.js"}

app/views/payments/error.html.haml
%h1 Error
%p 
  An error occurred: <%= @message %>

app/views/payments/mypayments.html.haml
.row
  .span2
  .span10
    %h1 Mes paiements

    = gravatar_image_tag current_user.email, alt: current_user
    %span.profile-name= current_user

    .balance-summary
      %h3 État de l'abonnement
      - if !current_user.is_active?
        = render '/application/flash'

      %ul{class: !current_user.is_active? && "disable-info"}
        %li
          Jours en flex :
          = current_user.flex_days
        %li Abonnement 

app/views/payments/subscription.html.haml
%h1 Paiement de la cotisation à Alsace Digitale
%p
  Montant de la cotisation : 20€

  Paiement via Paypal :
  = link_to image_tag('https://www.paypal.com/en_US/i/btn/btn_xpressCheckout.gif'), :action => 'subscription_checkout'

app/views/payments/subscription_config.html.haml
%h1 Paiement de la cotisation à Alsace Digitale
%p
  Merci !

app/views/shared/_top.html.haml
= render 'application/flash'

- if user_signed_in?
  %a
    = link_to 'Déconnexion', destroy_user_session_path, :method => :delete

%h1 Alsace Digitale - Gestion des membres

app/views/users/profile.html.haml
%h1 Profil utilisateur

= gravatar_image_tag current_user.email, alt: current_user
%span.profile-name= current_user

.balance-summary
  %h3 État de l'abonnement
  - if !current_user.is_active?
    = render '/application/flash'

  %ul{class: !current_user.is_active? && "disable-info"}
    %li
      Jours en flex :
      = current_user.flex_days
    %li Abonnement 